#define MAX_LINES 30
#define MAX_CHARS 256

#define CM_QUIT 108

#define CM_SAVE_BOOK   110

#define ID_RETURN_BUT  111

#define CM_EXP_BAD     112
#define CM_EXP_GOOD    113
#define CM_KEY_LEFT    114
#define CM_KEY_RIGHT   115
#define CM_KEY_UP      116
#define CM_KEY_DOWN    117
#define CM_KEY_LK_LEFT 118
#define CM_KEY_LK_RIGHT 119
#define CM_KEY_LK_UP   120
#define CM_KEY_LK_DOWN 121
#define CM_KEY_HOME    122
#define CM_KEY_INTO    123
#define CM_KEY_BACK    124
#define CM_KEY_PG_FW   125
#define CM_KEY_PG_BK   126
#define CM_KEY_OUTOF   127
#define CM_KEY_AT      128
#define CM_KEY_MINUS   129
#define CM_KEY_PLUS    130

#define CM_KEY_A       140
#define CM_KEY_B       141
#define CM_KEY_C       142
#define CM_KEY_D       143
#define CM_KEY_E       144
#define CM_KEY_F       145
#define CM_KEY_G       146
#define CM_KEY_H       147
#define CM_KEY_I       148
#define CM_KEY_J       149
#define CM_KEY_K       150
#define CM_KEY_L       151
#define CM_KEY_M       152
#define CM_KEY_N       153
#define CM_KEY_O       154
#define CM_KEY_P       155
#define CM_KEY_Q       156
#define CM_KEY_R       157
#define CM_KEY_S       158
#define CM_KEY_T       159
#define CM_KEY_U       160
#define CM_KEY_V       161
#define CM_KEY_W       162
#define CM_KEY_X       163
#define CM_KEY_Y       164
#define CM_KEY_Z       165
#define CM_KEY_COMMA   166
#define CM_KEY_SPACE   167
#define CM_KEY_1       168
#define CM_KEY_2       169
#define CM_KEY_3       170
#define CM_KEY_4       171
#define CM_KEY_5       172
#define CM_KEY_6       173
#define CM_KEY_7       174
#define CM_KEY_8       175
#define CM_KEY_9       176
#define CM_KEY_0       177
#define CM_KEY_COM     178
#define CM_KEY_PER     179



#define BT_WINDOW_INPUT    1
#define BT_WINDOW_OUTPUT   2
#define BT_WINDOW_GRAPHICS 3


